export const TYPES = {
    UtilityService: Symbol.for('UtilityService'),
    AWSFileFormatterHelper: Symbol.for('AWSFileFormatterHelper'),
    ConnectionPoolManager: Symbol.for("ConnectionPoolManager"),
    UserRepository: Symbol.for('UserRepository'),
    AccountUseCase: Symbol.for('AccountUseCae'),
    VehicleListingUseCase: Symbol.for('VehicleListingUseCase'),
    AuthUseCase: Symbol.for('AuthUseCase'),
    ChargingSessionUseCase: Symbol.for('ChargingSessionUseCase'),
    AuthService: Symbol.for('AuthService'),
    AuthenticationService: Symbol.for('AuthenticationService'),
    RegistrationService: Symbol.for('RegistrationService'),
    UserProfileService: Symbol.for('UserProfileService'),
    TransactionManager: Symbol.for('TransactionManager'),
    AuthMiddleware: Symbol.for('AuthMiddleware'),
    UserService: Symbol.for('UserService'),
    CarFeatureService: Symbol.for('CarFeatureService'),
    ChargerConnectorService: Symbol.for('ChargerConnectorService'),
    SMSService: Symbol.for('SMSService'),
    OTPService: Symbol.for('OTPService'),
    FileService: Symbol.for('FileService'),
    ReviewService: Symbol.for('ReviewService'),
    VehicleListingService: Symbol.for('VehicleListingService'),
    AWSHelper: Symbol.for('AWSHelper'),
    AuthServiceHelper: Symbol.for('AuthServiceHelper'),
    TokenService: Symbol.for('TokenService'),
    BaseService: Symbol.for('BaseService'),
    AuthHelpers: Symbol.for('AuthHelpers'),
    EmailService: Symbol.for('EmailService'),
    DatabaseInitializer: Symbol.for('DatanaseInitializer'),
    HttpClientFactory: Symbol.for('HttpClientFactory'),
    UserController: Symbol.for('UserController'),
    VerificationRepository: Symbol.for('VerificationRepository'),
    EVCarModelRepository: Symbol.for('EVCarModelRepository'),
    ChargerConnectorRepository: Symbol.for('ChargerConnectorRepository'),
    CarFeatureRepository: Symbol.for('CarFeatureRepository'),
    VehicleRepository: Symbol.for('VehicleRepository'),
    StationRepository: Symbol.for('StationRepository'),
    AuditRepository: Symbol.for('AuditRepository'),
    BookmarkRepository: Symbol.for('BookmarkRepository'),
    ActivitiesRepository: Symbol.for('ActivitiesRepository'),
    FileManagerRepository: Symbol.for('FileManagerRepository'),
    CheckinRepository: Symbol.for('CheckinRepository'),
    ReviewsRepository: Symbol.for('ReviewsRepository'),
    RatingsRepository: Symbol.for('RatingsRepository'),
    LinkedAccountsRepository: Symbol.for('LinkedAccountsRepository'),
    UserKYCRepository: Symbol.for('UserKYCRepository'),
    CheckInRepository: Symbol.for('CheckInRepository'),
    KYCService: Symbol.for('KYCService'),
    CheckInUseCase: Symbol.for('CheckInUseCase'),
    CheckInService: Symbol.for('CheckInService'),
    EVCarModelService: Symbol.for('EVCarModelService'),
    PaymentController: Symbol.for('PaymentController'),
    MockPaymentController: Symbol.for('MockPaymentController'),
    StripeWebhookService: Symbol.for('StripeWebhookService'),
    StripeWebhookController: Symbol.for('StripeWebhookController'),
    NRELService: Symbol.for('NRELService'),
    OpenChargeMapService: Symbol.for('OpenChargeMapService'),
    ChargetripService: Symbol.for('ChargetripService'),
    TomTomService: Symbol.for('TomTomService'),
    NHTSAVehicleService: Symbol.for('NHTSAVehicleService'),
    StationService: Symbol.for('StationService'),
    VehicleServices: Symbol.for('VehicleService'),
    VehicleUseCase: Symbol.for('VehicleUseCase'),
    ChargingStationUseCase: Symbol.for('ChargingStationUseCase'),
    NREL_API_BASE_URL: Symbol.for('NREL_API_BASE_URL'),
    NREL_API_KEY: Symbol.for('NREL_API_KEY'),
    OPEN_CHARGE_MAP_API_BASE_URL: Symbol.for('OPEN_CHARGE_MAP_API_BASE_URL'),
    OPEN_CHARGE_MAP_API_KEY: Symbol.for('OPEN_CHARGE_MAP_API_KEY'),
    TOMTOM_API_KEY: Symbol.for('TOMTOM_API_KEY'),
    CHARGETRIP_CLIENT_ID: Symbol.for('CHARGETRIP_CLIENT_ID'),
    CHARGETRIP_APP_ID: Symbol.for('CHARGETRIP_APP_ID'),
    NHTSA_API_BASE_URL: Symbol.for('NHTSA_API_BASE_URL'),
    GOOGLE_CLIENT_ID: Symbol.for('GoogleClientId'),
    GOOGLE_CLIENT_SECRET: Symbol.for('GoogleClientSecret'),
    GOOGLE_REDIRECT_URI: Symbol.for('GoogleRedirectUri'),
    GoogleService: Symbol.for('GoogleService'),
    ChargingStationRepository: Symbol.for('ChargingStationRepository'),
    ReviewReadQueryRepository: Symbol.for('ReviewReadQueryRepository'),
    CryptoService: Symbol.for('CryptoService'),
    // SmartCar API
    SmartCarService: Symbol.for('SmartCarService'),
    SMARTCAR_API_BASE_URL: Symbol.for('SMARTCAR_API_BASE_URL'),
    SMARTCAR_CLIENT_ID: Symbol.for('SMARTCAR_CLIENT_ID'),
    SMARTCAR_CLIENT_SECRET: Symbol.for('SMARTCAR_CLIENT_SECRET'),

    //MAPBOX API 
    MAPBOX_API_BASE_URL: Symbol.for('MAPBOX_API_BASE_URL'),
    MAPBOX_API_KEY: Symbol.for('MAPBOX_API_KEY'),
    MAPBOX_ACCESS_TOKEN: Symbol.for('MAPBOX_ACCESS_TOKEN'),
    // OCPP Service
    OCPPService: Symbol.for('OCPPService'),
    CsmsService: Symbol.for('CsmsService'),
    // Payment Service
    PaymentService: Symbol.for('PaymentService'),
    STRIPE_SECRET_KEY: Symbol.for('STRIPE_SECRET_KEY'),
    STRIPE_PRE_AUTH_AMOUNT: Symbol.for('STRIPE_PRE_AUTH_AMOUNT'),
    // Charging Session
    ChargingSessionService: Symbol.for('ChargingSessionService'),
    ChargingSessionRepository: Symbol.for('ChargingSessionRepository'),
    PaymentTransactionRepository: Symbol.for('PaymentTransactionRepository'),
    
    // KYC Service
} as const;

export const APP_VERSION = 'v1';
export const API_PATH = `api/${APP_VERSION}/charger`;
export const BASE_PATH = `api/${APP_VERSION}`;
export const APP_NAME = 'gr33nwh33lz_charging_station';
export const API_DOC_URL = '/';

export const delimeter = {
    S3_FileKey: '_',
    Directory: '/',
}

export const FileFormat: { [key: string]: string } = {
    JPEG : 'image/jpeg',
    JPG : 'image/jpg',
    PNG : 'image/png',
    GIF : 'image/gif',
    WEBP : 'image/webp',
    BMP : 'image/bmp',
    TIFF: 'image/tiff',
    ICO : 'image/ico',
    SVG : 'image/svg+xml',
    HTML: 'text/html',
    MP4 : 'video/mp4',
    MOV : 'video/quicktime',
    AVI : 'video/x-msvideo',
    WMV : 'video/x-ms-wmv',
    FLV : 'video/x-flv',
    MPEG : 'video/mpeg',
    MP3 : 'audio/mpeg',
    WAV : 'audio/wav',
    AAC : 'audio/aac',
    FLAC : 'audio/flac',
    OGG : 'audio/ogg',
    PDF : 'application/pdf',
    DOC : 'application/msword',
    DOCX : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',  
    XLS : 'application/vnd.ms-excel',
    XLSX : 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',  
    PPT : 'application/vnd.ms-powerpoint',
    PPTX : 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    TXT : 'text/plain',  
    CSV : 'text/csv',
    ZIP : 'application/zip',
    RAR : 'application/x-rar-compressed',
    TAR : 'application/x-tar',
    GZ : 'application/gzip',
    SEVENZ : 'application/x-7z-compressed',
}