export interface ChargingStationResponseDTO {
    _id: string;
    external_id: number | null;
    description: string | null;
    access_code: string | null;
    images?: string[] | null | undefined;
    access_days_time: string | null;
    access_detail_code: string | null;
    cards_accepted?: string[] | null | undefined;
    date_last_confirmed: string | null;
    expected_date: string | null;
    fuel_type_code: string | null;
    groups_with_access_code?: string[] | null | undefined;
    maximum_vehicle_class: string | null;
    open_date: string | null;
    owner_type_code: string | null;
    restricted_access: boolean | null;
    status_code: string | null;
    station_name: string | null;
    station_phone: string | null;
    updated_at: string | null;
    geocode_status: string | null;
    latitude: number | null;
    longitude: number | null;
    city: string | null;
    country: string | null;
    state: string | null;
    street_address: string | null;
    zip: string | null;
    ev_connector_types?: string[] | null | undefined;
    ev_dc_fast_num: number | null;
    ev_level1_evse_num: number | null;
    ev_level2_evse_num: number | null;
    ev_network: string | null;
    ev_network_web: string | null;
    ev_pricing: string | null;
    ev_renewable_source: string | null;
    ev_workplace_charging: boolean | null;
    facility_type: string | null;
    intersection_directions: string | null;

    //System based fields
    payment_options?: string[] | null | undefined;
    average_rating?: number;
    total_reviews?: number;
    popularity_score: number;
    provider: string | null;
    created_at: Date;
    last_updated: Date;
    __v: number;
}